# -*- coding: utf-8 -*-
"""DL-105: revert DL-103. The pointers come back; only the duplicate stays fixed."""
E = [
 ('manuscript/ch1.md','still there at dinner.\n','still there at dinner. Chapter 3 is where you learn to make it on purpose.\n'),
 ('manuscript/ch1.md','That is why the answer is a better game rather than more willpower.','That is why this chapter is called the Infinite Arcade, and it is why the answer is a better game rather than more willpower.'),
 ('manuscript/ch2.md','were on the line.\n','were on the line. Chapter 3 gives that exchange a name and a form.\n'),
 ('manuscript/ch3.md',"Two jobs, then: the Shaman's chapter, and the toolkit for the five faces that follow.","So Chapter 3 does two jobs. It serves as the Shaman's chapter and as the toolkit for the five faces that follow."),
 ('manuscript/ch3.md','Other people built some of these tools. Their names belong with them.','Other people built some of what this chapter hands you. Their names belong with the tools.'),
 ('manuscript/ch3.md','This is my remix, not the system it came from.','What follows is my remix, not the system it came from.'),
 ('manuscript/ch3.md','I am naming it here rather than in a footnote because my own fluency is already on the table as an','I am naming this in the chapter rather than in a footnote because Chapter 1 put my own fluency on the table as an'),
 ('manuscript/ch3.md','The Alchemist is a superpower, and it is the one you have been training.','The Alchemist is a superpower, the one this chapter trains.'),
 ('manuscript/ch4.md','The training is clarity without cruelty, held steady','What this chapter trains is clarity without cruelty, held steady'),
 ('manuscript/ch4.md','Every move here is a rehearsal for saying it once','Every move in this chapter is a rehearsal for saying it once'),
 ('manuscript/ch6.md','One piece of vocabulary here is borrowed and load-bearing','One piece of vocabulary in this chapter is borrowed and load-bearing'),
 ('manuscript/ch7.md','Both poles are real goods, and you are fluent in one of them and suspicious of the other.','Both poles are real goods, and this chapter is unusual in the book because its reader is fluent in one of them and suspicious of the other.'),
 ('manuscript/ch7.md','Contact is not the training here; the Bridge-Builder makes that in the first hour. The training is connection that has survived being told the truth.','This chapter does not train contact; the Bridge-Builder makes that in the first hour. It trains connection that has survived being told the truth.'),
 ('manuscript/ch8.md','That combination is the training, and the superpower has two halves.','That combination is what this chapter trains, and the superpower has two halves.'),
 ('manuscript/ch1.md','Some theater, now. Do it anyway.','What follows is a bit of theater. Do it anyway.'),
 ('manuscript/ch5.md','This is an account.','What follows is an account.'),
 ('appendices/APPENDIX_A_FOUR_ALLYSHIP_DOMAINS.md','A map of each territory:','What follows is a map of each territory:'),
 ('appendices/APPENDIX_B_QUESTS_CAMPAIGNS.md',"This isn't homework and it isn't a recap.","What follows isn't homework and it isn't a recap."),
 ('manuscript/ch1.md',"The words are Mayer, Davis, and Schoorman's.","The words are Mayer, Davis, and Schoorman's, and Appendix G says where to read them."),
 ('manuscript/ch3.md','I name their source when they arrive a few pages on.','I name their source when they arrive a few pages on. Appendix G says where to read each one.'),
 ('manuscript/ch6.md','and this book uses it in her sense throughout.','and this chapter uses it in her sense throughout. Appendix G says where to read her.'),
 ('manuscript/ch8.md','from folding into each other.','from folding into each other. Appendix G says where to read each one.'),
 ('appendices/APPENDIX_F_POLARITY_MAP.md','— is his.*','— is his. Appendix G says where to read him.*'),
 ('appendices/APPENDIX_B_QUESTS_CAMPAIGNS.md','Lost which daemon or domain is yours right now? The diagnostic is in Appendix A.*','Lost which daemon or domain is yours right now? Appendix A has the diagnostic.*'),
 ('manuscript/ch2.md','You should be able to name:','By the end of this chapter, you should know:'),
 ("manuscript/ch3.md","The Alchemist leads with it; the other five are in Appendix I.","The Alchemist leads with it. Appendix I lays them all out."),
 ("manuscript/ch7.md","Every move here is an instrument for making that sentence true.","Every move in this chapter is an instrument for making that sentence true."),
 ("manuscript/ch8.md","Each move above exists to make that sentence true.","That sentence is what every move in this chapter is for."),
]
