# -*- coding: utf-8 -*-
"""DL-100: the locative "land" goes too. Only the skeeball ball and the noun stay."""
E = [
 ("manuscript/ch1.md","a decision lands on the person with the least power to absorb it, and the temperature drops",
  "a decision falls on the person with the least power to absorb it, and the temperature drops"),
 ("manuscript/ch1.md","The payout lands in my safety and my belonging","The payout goes to my safety and my belonging"),
 ("manuscript/ch1.md","that the decision was landing on the person with the least power to absorb it",
  "that the decision was falling on the person with the least power to absorb it"),
 ("manuscript/ch1.md","because a move that lands on nobody is one the arrangement gets for free",
  "because a move that reaches nobody is one the arrangement gets for free"),
 ("manuscript/ch1.md","If that mix-up had landed on anyone else in the building","If that mix-up had hit anyone else in the building"),
 ("manuscript/ch1.md","Keep showing up where the break could land","Keep showing up where the break could come"),
 ("manuscript/ch1.md","Chance needs you present for years before the jackpot lands","Chance needs you present for years before the jackpot comes"),
 ("manuscript/ch2.md","and repair has to land there, so allyship put all of its tools there",
  "and repair has to happen there, so allyship put all of its tools there"),
 ("manuscript/ch2.md","The offer lands on something older than the offer","The offer meets something older than the offer"),
 ("manuscript/ch3.md","name where a feeling landed in the body before naming what it means",
  "name where a feeling shows in the body before naming what it means"),
 ("manuscript/ch3.md","The cost landed somewhere the villagers never thought to look","The cost fell somewhere the villagers never thought to look"),
 ("manuscript/ch3.md","The tightening did not land on the correction.","The tightening was not about the correction."),
 ("manuscript/ch3.md","It landed a second later, when Ines did not change her face","It came a second later, when Ines did not change her face"),
 ("manuscript/ch3.md","You noticed where it landed in your body before you had a sentence",
  "You noticed where it showed in your body before you had a sentence"),
 ("manuscript/ch4.md","the *hey, I hope that landed okay* sent three hours later","the *hey, I hope that was okay* sent three hours later"),
 ("manuscript/ch4.md","The four domains are where the line finally lands:","The four domains are where the line finally gets drawn:"),
 ("manuscript/ch6.md","Clean Up: locate where it landed, and stabilize there","Clean Up: locate where it shows, and stabilize there"),
 ("manuscript/ch6.md","The cost lands on the people the design is for.","The cost falls on the people the design is for."),
 ("manuscript/ch6.md","the channel, the place it landed, what it did","the channel, the place it showed, what it did"),
 ("manuscript/ch7.md","The cost lands in exactly the place this chapter cannot afford to lose it",
  "The cost is paid in exactly the place this chapter cannot afford to lose it"),
 ("manuscript/ch8.md","The cost lands precisely where this chapter cannot afford it",
  "The cost comes out of precisely what this chapter cannot afford"),
 ("front_matter/headmasters_letter.md","The shape of a term is the same wherever you land.","The shape of a term is the same wherever you go."),
 ("back_matter/glossary.md","A reading that never lands in one of them\nstayed a reading",
  "A reading that never reaches one of them\nstayed a reading"),
 ("back_matter/glossary.md","and a small move at a narrow\ndoor still lands","and a small move at a narrow\ndoor still counts"),
 # the three mantra lines: not a taught line, so they vary
 ("manuscript/ch3.md","know: \"I get it. You got through.\"","know: \"I get it. You reached me.\""),
 ("manuscript/ch3.md","Your system says \"I understand. You got through.\"","Your system says \"I understand. I have it.\""),
 ("manuscript/ch3.md","*I get it. You got through.* Then finish the sentence","*I get it. I heard you.* Then finish the sentence"),
]
