# -*- coding: utf-8 -*-
E = [
 ("ch1.md","a move that lands wrong does not only cost you","a move that goes wrong does not only cost you"),
 ("ch1.md","and that lands late, sometimes years late, while the performance lands at once",
           "and that shows up late, sometimes years late, while the performance is seen at once"),
 ("ch1.md","A sentence in somebody else's book lands hard enough that I stop reading",
           "A sentence in somebody else's book stops me mid-page"),
 ("ch1.md","When something landed hard, I wrote it on a card","When something stopped me, I wrote it on a card"),
 ("ch2.md","doesn't come with enough context to land cleanly","doesn't come with enough context to be understood"),
 ("ch2.md","*\"I think that landed as anger.","*\"I think that came across as anger."),
 ("ch3.md","lets the truth land as care instead of an ambush","lets the truth be heard as care instead of an ambush"),
 ("ch4.md","You don't need it to land well.","You don't need it to go well."),
 ("ch4.md","A joke lands wrong and the moment closes over it","A joke goes wrong and the moment closes over it"),
 ("ch4.md","The cost lands twice:","The cost falls twice:"),
 ("ch4.md","Anger delivered as anger lands hard and lands clean, because Fire asks for agency",
           "Anger delivered as anger is hard to hear and easy to answer, because Fire asks for agency"),
 ("ch4.md","Hurt delivered as anger lands as an attack","Hurt delivered as anger is heard as an attack"),
 ("ch6.md","proposals sometimes land as enormous","proposals sometimes read as enormous"),
 ("ch6.md","the last time a decision landed badly","the last time a decision went badly"),
 ("ch6.md","within an hour of something landing wrong","within an hour of something going wrong"),
 ("ch6.md","the last decision that landed badly on people who had no say in it",
           "the last decision that went badly for people who had no say in it"),
 ("ch7.md","because a term might land badly, and something that lands badly is harm",
           "because a term might go badly, and something that goes badly is harm"),
 ("ch7.md","that something you did landed badly on them","that something you did hurt them"),
 ("ch7.md","The close lands clean when there's nothing left to add","The close is clean when there's nothing left to add"),
 ("ch7.md","If it is still landing as entirely your fault","If it still reads as entirely your fault"),
 ("ch8.md","I have watched that land as\n> loss in students who expected it to land as freedom",
           "I have watched that arrive as\n> loss in students who expected freedom"),
 ("ch8.md","and the line lands correctly","and the line is correct"),
 ("ch8.md","it lands harder on the Sage than on the five before","it is harder on the Sage than on the five before"),
 ("ch9.md","when someone says something that lands wrong","when someone says something that stings"),
 ("ch9.md","The question at the end of this book lands simpler and harder",
           "The question at the end of this book is simpler and harder"),
 ("ch9.md","let the failure land at full strength","let the failure run at full strength"),
 ("ch9.md","default to their home face the moment something lands hard",
           "default to their home face the moment something stings"),
 ("ch9.md","people who can run it when something lands hard","people who can run it when something stings"),
 ("ch9.md","says something in a team meeting that lands hard on the newest person at the table",
           "says something in a team meeting that the newest person at the table takes hard"),
]
