# -*- coding: utf-8 -*-
"""DL-99 tranche 2: `land` in the reception sense. 42 spans; 26 locative uses kept."""
E = [
 ("ch1.md","The help never lands, because you were looking at the scoreboard","The help never arrives, because you were looking at the scoreboard"),
 ("ch1.md","it needs a history behind it before it lands at all","it needs a history behind it before it counts at all"),
 ("ch1.md","because you happened to be there to send it, lands the right person the job","because you happened to be there to send it, gets the right person the job"),
 ("ch2.md","By the time that lands, something has usually already been spent","By the time that registers, something has usually already been spent"),
 ("ch2.md","When a daemon lands, stop there.","When a daemon fits, stop there."),
 ("ch2.md","a hard email lands and the Protector runs it as a physical threat","a hard email arrives and the Protector runs it as a physical threat"),
 ("ch3.md","to neutral (the feeling landed, its message received)","to neutral (the feeling finished, its message received)"),
 ("ch3.md","know: \"I get it. The message landed.\"","know: \"I get it. You got through.\""),
 ("ch3.md","Your system says \"I understand. The message landed.\"","Your system says \"I understand. You got through.\""),
 ("ch3.md","*I get it. The message landed.* Then finish the sentence","*I get it. You got through.* Then finish the sentence"),
 ("ch3.md","Cashed in, joy evaporates; landed in, it completes into bliss","Cashed in, joy evaporates; stayed in, it completes into bliss"),
 ("ch3.md","Softening anger so the truth can land may cost you","Softening anger so the truth can be heard may cost you"),
 ("ch4.md","The lines land now.","The lines hold now."),
 ("ch4.md","in the seconds after a clean line lands","in the seconds after a clean line is drawn"),
 ("ch4.md","Before the name landed, while it was still just running","Before the name took, while it was still just running"),
 ("ch4.md","when the charge lands, start a clock instead of a sentence","when the charge arrives, start a clock instead of a sentence"),
 ("ch5.md","designed to stop your questions from landing","designed to stop your questions from going anywhere"),
 ("ch5.md","the inheritance lands, on time, doing its job","the inheritance arrives, on time, doing its job"),
 ("ch5.md","if I commit before the repair lands?","if I commit before the repair is done?"),
 ("ch6.md","Something lands. Before it has finished landing","Something arrives. Before it has finished arriving"),
 ("ch6.md","a quarter-second after the signal lands","a quarter-second after the signal arrives"),
 ("ch7.md","tolerate their own partiality lands in a false neutrality","tolerate their own partiality ends in a false neutrality"),
 ("ch7.md","You let the hard sentence land, and you stay","You say the hard sentence, and you stay"),
 ("ch7.md","you agreed with them out loud without anything landing","you agreed with them out loud without anything changing"),
 ("ch7.md","The move either lands and the conversation opens","The move either works and the conversation opens"),
 ("ch7.md","A term that lands before they have heard you describe their side","A term said before they have heard you describe their side"),
 ("ch8.md","What landed instead was:","What they heard instead was:"),
 ("ch8.md","from what has actually landed with these people before","from what has actually reached these people before"),
 ("ch8.md","and what has actually landed with\n   these people before is","and what has actually reached\n   these people before is"),
 ("ch8.md","*here's where I landed, and I'm staying.*","*here's where I came out, and I'm staying.*"),
 ("ch9.md","when you read the news and feel it land","when you read the news and feel it hit"),
]
APPX = [
 ("appendices/APPENDIX_A_FOUR_ALLYSHIP_DOMAINS.md","take it at the level where it will actually land","take it at the level where it will actually work"),
 ("appendices/APPENDIX_A_FOUR_ALLYSHIP_DOMAINS.md","the story that lands only for people who already know","the story that reaches only people who already know"),
 ("appendices/APPENDIX_A_FOUR_ALLYSHIP_DOMAINS.md","in language that lands where action is possible","in language that reaches where action is possible"),
 ("appendices/APPENDIX_C_FIVE_CHANNELS.md","Someone says something that lands as criticism","Someone says something that you hear as criticism"),
 ("appendices/APPENDIX_C_FIVE_CHANNELS.md","That question landed as an attack, but I know my own capacity","I took that question as an attack, but I know my own capacity"),
 ("appendices/APPENDIX_C_FIVE_CHANNELS.md","You let it land fully.","You let it run fully."),
 ("appendices/APPENDIX_C_KEY_TERMS.md","When the Skeptic's doubt lands at the reader's capacity","When the Skeptic's doubt aims at the reader's capacity"),
 ("appendices/APPENDIX_H_CHARACTER_SHEET.md","Rewriting other people's emails so they land softer","Rewriting other people's emails so they read softer"),
 ("back_matter/enrollment.md","If the Shaman chapter landed hardest, read it next","If the Shaman chapter hit hardest, read it next"),
 ("back_matter/glossary.md","somebody said the unsaid charge, and it landed","somebody said the unsaid charge, and it was heard"),
]
